# Generated by Django 4.0 on 2021-12-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ours', '0004_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
